# Generated by Django 3.2.12 on 2022-12-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0008_use_native_slugfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='entity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='generic_value_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
